spring:
  profiles.active: dev

---

spring:
  profiles: dev
  jpa:
    show-sql: true
  jackson.serialization.INDENT_OUTPUT: true
server:
  context-path: /api
  port: 8090
#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG

app.token.header: X-Auth-Token
app.token.secret: ca$hc0w1!
